### PR TITLE
Update Create Product

### PR DESCRIPTION
**Pull request by schnajos**
RECAP Issues pointed out by @KnownInter: 
1. The heading is too big
2. Again some unnecessary css code
3. The user feedback regarding errors is inside the selector instead of being below it
4. Why is there no status in the formGroup? It can't be null when submitting the form
5. Remove console.log if you don't need it
6. Don't use type definitions in the service functions since they are already declared

---

WHAT HAS CHANGED:
1. Heading scales back and has more letter spacing on screens <500px wide. Otherwise, I do not think the heading should be smaller as the large heading gives the user clearer/more obvious feedback on what page they are. This styling is of course up for debate in one of the zoom meetings. For now, I'll adjust all pages to the same styling. (Not sure why Login & SignUp reverted back to the old css)
2. I removed some css code. I don't see anything else possible to remove.
3. Fixed
4. Fixed
5. Removed
6. PENDING... I don't understand what exactly to change. Doesn't it have to generate a new ProductForm from scratch?

### CODE REVIEW

**Comment by schnajos** [comment]
### Option selector OR Check list for 'status' and 'deliverable'?
Besides being more consistent, I think with the option selector it is clearer to the user what the platform actually means by status and deliverable. They have the option between two clear sentences rather than checking a nondescript box.
What do you think?

**Review by KnownInter — CHANGES_REQUESTED** [review]
> 1. Heading scales back and has more letter spacing on screens <500px wide. Otherwise, I do not think the heading should be smaller as the large heading gives the user clearer/more obvious feedback on what page they are. This styling is of course up for debate in one of the zoom meetings. For now, I'll adjust all pages to the same styling. (Not sure why Login & SignUp reverted back to the old css)

I disagree, but we can discuss it in a meeting. For now adjust the component's design to the other ones (e.g edit-product.component), so that we have some design consistency. If you want to update the design, feel free to do it, but do it everywhere. Keep in mind that the design update is our least problem at the moment, and that you should focus on implementing the necessary functions. After that you can update the UI.
> 3. Fixed

The feedback should be consistent! Do not only use 'required!' as error feedback. Also there are some validations missing (look up edit-product.component)
> 5. Removed

There is still some unnecessary code in the ts file.
> 6. PENDING... I don't understand what exactly to change. Doesn't it have to generate a new ProductForm from scratch?

https://github.com/scg-unibe-ch/ese2020-team5/blob/fa942fab24f7808fc85aa4aaf066ee448856fda4/frontend/src/app/components/create-product/create-product.component.ts#L57 '(data: any)' is unnecessary and wrong, since the ouput is of type product, which is already declared in the product service. So there is no need for you to add the any type (same goes for '(error: any)').
> ### Option selector OR Check list for 'status' and 'deliverable'?
> Besides being more consistent, I think with the option selector it is clearer to the user what the platform actually means by status and deliverable. They have the option between two clear sentences rather than checking a nondescript box.
> What do you think?

Selectors for true/false questions are unnecessary.

**Comment by schnajos** [comment]
1. It makes no sense to revert back to the old design, when it's already implemented everywhere (except SignIn and Login for some reason). Everything should be updated/kept at the newer version that we already showed in Milestone 1. The other PRs will include all the other pages in the design seen here. We can discuss from there, once all are merged.

3. fixed the error messages

5. Not sure what 🙈

6. Is this correct? It works when I test it but not sure how it's actually supposed to be.

Selector question: I think checkboxes look inconsistent, and it's not as clear as the menu promts...I'll leave it for now and to be discussed wednesday. The chosen option, I'll adjust in the page where it needs to be the other way

**Comment by schnajos** [comment]
Other consistency issues in other pages (eg. price format not being CHF), I'll adjust in a seperate UI update PR. But first Shopping cart 😬

**Review by KnownInter — APPROVED** [review]

**Pull request merged**
