### PR TITLE
create transaction

### PR DESCRIPTION
**Pull request by dominiqueroux**
Added the controller / service / model for a transaction.
The service currently supports only the adding of a transaction to the DB.
No money exchange etc. is made.
Already made the association with the User.

Will wait until the integration test PR is in the master, then I can add the integration test to the transaction as well.

### CODE REVIEW

**Review by JethroWarnett — CHANGES_REQUESTED** [review]
* In transaction.model.ts, you should add the attribute date (for querying I would recommend year, month, day)
* In transaction.model.ts, if seller, buyer or product are deleted, I would not set it to NULL. You lose information. Did the seller sell to the same user or to different users, etc. We can always look in the database if the users or product still exist
* In transaction.service you have transaction is constant, but you change values. This is not allowed. Use "let" instead
* In transaction.service you nest your then catch statements. I would split it up or don't add a second catch statement
* In transaction.service use an interface instead of a request. I don't know what the necessary values are, that I need to pass

**Comment by dominiqueroux** [comment]
> * In transaction.model.ts, you should add the attribute date (for querying I would recommend year, month, day)

This is added automatically by sequelize

> * In transaction.model.ts, if seller, buyer or product are deleted, I would not set it to NULL. You lose information. Did the seller sell to the same user or to different users, etc. We can always look in the database if the users or product still exist

I do not agree on that: If we leave the userId, the only thing we see is that there would be different seller, but nothing more. Therefore, in my opinion, if a user deletes his/her account we already lose all important information and could aswell set the sellerId to NULL

**Response**: I agree we loose the most important information, but we don't loose all information. Suppose we query "find all sellers with loyal customers (customers that have bought from the same seller at least say 5 times)". If we set the data the NULL, we might loose sellers in this query. If needed we can always revert this decision.

> * In transaction.service you have transaction is constant, but you change values. This is not allowed. Use "let" instead

I think I don't change transaction, but transaction."attributes" (even intellij forces me to use const)

> * In transaction.service you nest your then catch statements. I would split it up or don't add a second catch statement

:+1:

**Review by JethroWarnett — CHANGES_REQUESTED** [review]
* In shoppingcart.service.ts, a shopping cart should not receive transactions, it should create transactions. When a user wants to buy products, the shopping cart browses the database for all rows with the userId. For each row, create a transaction with userId and associated productId.

Minor Comments:
* In shoppingcart.service.ts you should use interfaces not request, so

public create(req: Request, buyerId: number): Promise<TransactionAttributes>

should become 

public create(transaction: TransactionAttributes, buyerId: number): Promise<TransactionAttributes>

otherwise its difficult to understand your code

* In shoppingcart.service.ts, you don't need to use parseInt for the productId. Sequelize will also accept a string representation

**Comment by dominiqueroux** [comment]
> * In shoppingcart.service.ts, a shopping cart should not receive transactions, it should create transactions. When a user wants to buy products, the shopping cart browses the database for all rows with the userId. For each row, create a transaction with userId and associated productId.
> 
> Minor Comments:
> 
> * In shoppingcart.service.ts you should use interfaces not request, so
> 
> public create(req: Request, buyerId: number): Promise
> 
> should become
> 
> public create(transaction: TransactionAttributes, buyerId: number): Promise
> 
> otherwise its difficult to understand your code
> 
> * In shoppingcart.service.ts, you don't need to use parseInt for the productId. Sequelize will also accept a string representation

Totally agree on that.
Will implement this.
Thanks for the review

**Review by JethroWarnett — COMMENTED** [review]
Review:
* In shoppingcart.service.ts, you don't set attribute amountOrTime.
* In shoppingcart.service.ts, when you reject product, you should also return the product title.
* (Minor) In shoppingcart.service.ts, you nest your then/catch statements

Things todo:
* In shoppingcart.service.ts, you need to check if the buyer has enough credits
* In transaction.service.ts, you need to deduct credits from buyer and add them to seller
* In transaction.service.ts, you need to update the product status

**Comment by dominiqueroux** [comment]
Updated several things, integration tests will fail (=> changed some parts of the code, but currently not updated the integration tests)

**Review by JethroWarnett — COMMENTED** [review]
If the code runs and there are no conflicts, then merge the pull request for milestone 3.

But shoppingcart.service.ts and transaction.service.ts are very hard to read and your repeat code (for example you double check if the user has enough credits). I would add comments or make the code descriptive by using help functions.

**Review by JethroWarnett — APPROVED** [review]
Looks great

**Pull request merged**
