### PR TITLE
Added a new getter on products:

### PR DESCRIPTION
**Pull request by dominiqueroux**
get on /products/:id will get an (approved) product

### CODE REVIEW

**Review by KnownInter — CHANGES_REQUESTED** [review]
Unapproved products should also be sent if the requestee is the owner of the product.

**Review by JethroWarnett — COMMENTED** [review]
* In product.service.ts, you nest you then/catch statements, which makes your code harder to understand.

**Comment by dominiqueroux** [comment]
> * In product.service.ts, you nest you then/catch statements, which makes your code harder to understand.

Thanks for the reply, but as far as I see it, I cannot resolve the nesting, since some Promises need the result from the earlier resolved Promises

**Review by JethroWarnett — APPROVED** [review]
Looks fine

**Comment by dominiqueroux** [comment]
Fixed merge conflict

**Pull request merged**
