### PR TITLE
CRC Cards frontend+UML Diagram Update 1

### PR DESCRIPTION
**Pull request by Thirith98**
Please Recheck

### CODE REVIEW

**Review by KnownInter — CHANGES_REQUESTED** [review]
The UML Diagram still looks wrong. There are a lot of things missing like the services and a lot of the variables don't make sense (at least to me).

**Review by Thirith98 — COMMENTED** [review]
Ok

**Comment by Thirith98** [comment]
> 
[crcCards-frontend_update 02.11.2020.docx](https://github.com/scg-unibe-ch/ese2020-team5/files/5476628/crcCards-frontend_update.02.11.2020.docx)

**Comment by dominiqueroux** [comment]
Closing this one, since I think this is deprecated

**Pull request closed without merging**
